apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: keepalived-vip
  namespace: kube-system
spec:
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: keepalived-vip
    spec:
      nodeSelector:
        run-ingress: "true"
      containers:
        - name: keepalived
          image: jurgis/keepalived:2.0.7.8
          securityContext:
            privileged: true
          volumeMounts:
            - name: config-volume
              mountPath: /etc/keepalived/config/
              readOnly: true
            - name: secrets-volume
              mountPath: /etc/keepalived/secrets/
              readOnly: true
      hostNetwork: true
      volumes:
        - name: config-volume
          configMap:
            name: keepalived-conf
        - name: secrets-volume
          secret:
            secretName: keepalived-secrets
