apiVersion: v1
kind: Service
metadata:
  name: keepalived-vip
  namespace: kube-system
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: fake
    port: 1
    protocol: TCP
    targetPort: 1
  selector:
    app: keepalived-vip
